#!/bin/bash

#requires xcode to be installed and the xcode terminal tools to be installed

#install xcode command line tools
#xcode-select --install

#ensure brew is installed
if [ command -v brew >/dev/null 2>&1 ]; then
	echo "Brew not installed. Installing Brew..." 
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	
	brew doctor

	# so that brew install does not require root privledge
	sudo chown -R $USER /usr/local/*
fi

echo "Installing Homebrew packages..."
brew update

# to install apps like chrome that aren't development packages
# https://github.com/caskroom/homebrew-cask
brew install caskroom/cask/brew-cask

# fish shell
brew install fish 

# macvim
brew install macvim 

# regular vim
brew install vim

# go sometimes pulls down mercurial repositories
brew install mercurial

brew install wget

brew install tree

# a better ack/grep
brew install the_silver_searcher

# Fast GitHub client
brew install gh

brew install packer

# github .gitignore templates
brew install gibo

# this directory is required by gibo
if [ ! -d $HOME/.gitignore-boilerplates ]; then
	mkdir $HOME/.gitignore-boilerplates
fi

brew install phash
brew install cmake
brew install cimg
brew install ffmpeg
brew install lua

# Fuzzy finder
brew install fzf

# Ruby version manager
brew install rbenv

# So `rbenv install` works
brew install ruby-build

# `brew services` without the warnings that come from the `brew services` in
# homebrew/boneyard
brew tap gapple/services

brew tap caskroom/cask
brew install brew-cask

#brew cask install skype
#brew cask install dropbox

#vagrant and virtualbox vm
brew cask install vagrant
brew cask install virtualbox

# video player
brew cask install vlc

#Terminal replacement
brew cask install iterm2

#Documentation for almost all languages, also snippet manager
brew cask install dash

#make fish default shell
#chsh -s /usr/local/bin/fish
