#!/bin/bash

if [ "$(uname -s)" != "Darwin" ]; then
  exit 0
fi

#requires xcode to be installed and the xcode terminal tools to be installed

#install xcode command line tools
xcode-select --install

#ensure brew is installed
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Remove Old Brew?
#if [ command -v brew >/dev/null 2>&1 ]; then
#	echo "Brew not installed. Installing Brew..." 
#	brew doctor
	# so that brew install does not require root privledge
#	sudo chown -R $USER /usr/local/*
#fi
# End Remove Old Brew

echo "Updating Homebrew packages..."
brew update

# to install apps like chrome that aren't development packages
# https://github.com/caskroom/homebrew-cask
brew install caskroom/cask/brew-cask

# needed for version control info on the shell
brew install vcprompt

# zsh shell
brew install zsh

# fish shell
# brew install fish 

# macvim
brew install macvim --with-cscope --with-lua --override-system-vim

# go sometimes pulls down mercurial repositories
brew install mercurial

brew install wget

brew install tree

brew tap caskroom/cask
brew install brew-cask

brew install gpg
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

# a better ack/grep
brew install the_silver_searcher

# Fast GitHub client in go
# brew install gh

# github .gitignore templates
# brew install gibo

# this directory is required by gibo
if [ ! -d $HOME/.gitignore-boilerplates ]; then
	mkdir $HOME/.gitignore-boilerplates
fi

#Terminal replacement
brew cask install iterm2

# visual diff
brew cask install p4merge

# c++ library
# brew install boost

# event notification library
# brew install libevent

# video player
brew cask install vlc

#http://www.economyofeffort.com/2014/08/11/beyond-ctrl-remap-make-that-caps-lock-key-useful/
brew cask install karabiner
#seil is not necessary if you set the system preferences for caps lock to control

#vagrant and virtualbox vm
brew cask install vagrant
brew cask install virtualbox
#brew cask install chefdk

#docker
brew install boot2docker

# http://docs.oracle.com/cd/E37670_01/E41138/html/ch11s07.html
# https://github.com/brona/iproute2mac
brew tap brona/iproute2mac
brew install iproute2mac

# IRC client
brew cask install limechat

sudo easy_install pip
sudo pip install ansible --quiet
sudo pip install --upgrade bumpversion

# nodejs
# brew install node

# Fuzzy finder
#brew install fzf

# install modern ruby version manager
#brew install rbenv ruby-build
#rbenv install 2.2.0

#Documentation for almost all languages, also snippet manager
# brew cask install dash

## IMAGE Manipulation
# http://www.imagemagick.org/
# brew install imagemagick
# brew install phash
# brew install cmake
# brew install cimg
# brew install ffmpeg
# brew install lua
# brew install git-extras

# VIPS imaging library 
# https://github.com/jcupitt/ruby-vips/wiki/installation-on-various-platforms
# brew tap homebrew/science
# brew install vips

# for editing gifs
# brew install giflib

# make zsh the default shell
chsh -s /usr/local/bin/zsh
