#!/bin/bash

# install and run with this command
# curl -L https://raw.github.com/franklinwise/dotfiles/master/install | bash

DOTDIR=$HOME/.settings/dotfiles

if [ ! -d $DOTDIR ]; then
    	#echo ".settings/dotfiles not found, pulling from github."
	#if [ ! -a $HOME/.gitconfig ]; then 
	#	# .ssh keys need to be set up outside of this script
	#	curl -o $HOME/.gitconfig -L https://raw.github.com/franklinwise/dotfiles/master/home/gitconfig  
	#fi
	#git clone https://github.com/franklinwise/dotfiles.git $DOTDIR
fi

cd $DOTDIR

set -e

CONFIG="install.conf.yml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}/"

echo "Basedir set to ${BASEDIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

