#!/bin/bash

# manually requires p4merge to be downloaded and installed
# spf13 vim
curl http://j.mp/spf13-vim3 -L -o - | sh

# zsh needs to be setup to be used the first time, or the .zshrc file needs to be in place, indicating it's setup
zsh

# make zsh the default shell
chsh -s /usr/local/bin/zsh

#setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
