#!/bin/bash

# auto setup p4merge 
# http://pempek.net/articles/2014/04/18/git-p4merge/

wget -P /usr/local/bin http://pempek.net/files/git-p4merge/mac/p4merge
chmod +x '/usr/local/bin/p4merge'
git config --global merge.tool p4merge
git config --global mergetool.keepTemporaries false
git config --global mergetool.prompt false

# spf13 vim
curl http://j.mp/spf13-vim3 -L -o - | sh

# zsh needs to be setup to be used the first time, or the .zshrc file needs to be in place, indicating it's setup
zsh

# make zsh the default shell
chsh -s /usr/local/bin/zsh

#setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
