#!/bin/bash

# .bash_profile vs .bashrc
# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
# .bashrc executed every new shell, vs .bash_profile is run first login

# Set architecture flags
export ARCHFLAGS="-arch x86_64"
# Ensure user-installed binaries take precedence
export PATH=/usr/local/bin:$PATH
# Load .bashrc if it exists
test -f ~/.bashrc && source ~/.bashrc

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi


export PS1="\u@\h \w: "
alias ls='command ls -G'
alias splunk='splunk.sh'
PATH=$PATH:$HOME/src/scripts
alias showHiddenFiles='defaults write com.apple.finder AppleShowAllFiles YES;
killall Finder /System/Library/CoreServices/Finder.app'
alias hideHiddenFiles='defaults write com.apple.finder AppleShowAllFiles NO;
killall Finder /System/Library/CoreServices/Finder.app'
eval "$(chef shell-init bash)"
