#!/bin/bash

9 [[ -r $HOME/.bash_rc ]] && . $HOME/.bash_rc

# For bash, put stuff in ~/.bashrc, and make ~/.bash_profile source it.
# For zsh, put stuff in ~/.zshrc, which is always executed.
# https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

