# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export EDITOR=mvim

export GOPATH=$HOME/src/go
export GOROOT=/usr/local/go

export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
export CHEF_DRIVER="vagrant"
export EDITOR="mvim"

export GEM_HOME="$HOME/.chefdk/gem/ruby/2.1.0"
export GEM_PATH="$HOME/.chefdk/gem/ruby/2.1.0:/opt/chefdk/embedded/lib/ruby/gems/2.1.0"
export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/2.1.0"
export XDG_CONFIG_HOME="$HOME/.config"
export RBENV_ROOT=/usr/local/var/rbenv

ZSH_CUSTOM=$HOME/.config/zsh/

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


# Look in ~/.oh-my-zsh/themes/
#https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="terminalparty-fw"
#"ys" "wedisagree" "sorin" "gallois" "fishy"

DEFAULT_USER="wise"

# found in ~/.oh-my-zsh/plugins/*)
# Add wisely, as too many plugins slow down shell startup.
#https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
plugins=(git vagrant wd)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/opt/chefdk/bin/:/opt/chefdk/embedded/bin:/Users/wise/src/go/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
