#!/bin/zsh

##################
#  SOURCE PROFILE
##################

[[ -r $HOME/.profile ]] && . $HOME/.profile

##################
#  ENVIRONMENT
##################

export EDITOR=mvim
export LANG=en_US.UTF-8
export XDG_CONFIG_HOME="$HOME/.config"

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.config/zsh/

export MYGO=$HOME/src/go/src/github.com
export GOPATH=$HOME/src/go
export GOROOT=/usr/local/go

export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
export CHEF_DRIVER="vagrant"
export EDITOR="mvim"

export ARCHFLAGS="-arch x86_64"

# export SSH_KEY_PATH="~/.ssh/dsa_id"
# export RBENV_ROOT=/usr/local/var/rbenv

##################
#  PATH
##################

export PATH="$GOPATH/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:$GOROOT/bin:$HOME/Applications:$PATH"

##################
#  PLUGINS
#
#   found in ~/.oh-my-zsh/plugins/* [too many will slow things down]
#   https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
##################

plugins=(git vagrant wd)

##################
#  THEMES OH-MY-ZSH
#
#  Look in ~/.oh-my-zsh/themes/
#  https://github.com/robbyrussell/oh-my-zsh/wiki/themes
#  "ys" "wedisagree" "sorin" "gallois" "fishy"
##################

ZSH_THEME="terminalparty-fw"
DEFAULT_USER="wise"

source $ZSH/oh-my-zsh.sh

###################

# ZSH auto correct
ENABLE_CORRECTION="true"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

##################
#  ALIASES
##################

[[ -r $HOME/.config/aliases ]] && . $HOME/.config/aliases


## END ##

##################
#  RUBY
##################

eval "$(rbenv init -)"
rbenv global 2.2.0


