# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
#	config.omnibus.chef_version = :latest
	
#	enabling berkshelf here breaks test kitchen
	config.berkshelf.enabled = false

	config.vm.provider "vmware_fusion" do |v|
#		v.vmx["memsize"] = "512"
#		v.vmx["numvcpus"] = "2"
	end
	config.vm.provider "virtualbox" do |v|
#		v.memory = 512
#		v.cpus = 2
	end
end
