# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.omnibus.chef_version = :latest
	config.berkshelf.enabled = true

	config.vm.provider "vmware_fusion" do |v|
		v.vmx["memsize"] = "512"
		v.vmx["numvcpus"] = "4"
	end
	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 2
	end
end
