#!/bin/bash

if [ "$(uname -s)" != "Darwin" ]; then
  exit 0
fi

echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

#echo "Disable the 'Are you sure you want to open this application?' dialog"
#defaults write com.apple.LaunchServices LSQuarantine -bool false

#echo "Automatically illuminate built-in MacBook keyboard in low light"
#defaults write com.apple.BezelServices kDim -bool true

#echo "Turn off keyboard illumination when computer is not used for 5 minutes"
#defaults write com.apple.BezelServices kDimTime -int 300

echo "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

echo "Finder: Always open everything in column view"
defaults write com.apple.Finder FXPreferredViewStyle clmv

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Menu bar: hide the Time Machine, Volume, and User icons
# for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
#	defaults write "${domain}" dontAutoLoad -array \
#		"/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
#		"/System/Library/CoreServices/Menu Extras/Volume.menu" \
#		"/System/Library/CoreServices/Menu Extras/User.menu"
#done

#
# DOCK
#
# Setting the icon size of Dock items to 36 pixels for optimal size/screen-realestate
#defaults write com.apple.dock tilesize -int 36

echo "Make Dock icons of hidden applications translucent"
defaults write com.apple.dock showhidden -bool true

# Show remaining battery time; hide percentage
#defaults write com.apple.menuextra.battery ShowPercent -string "NO"
#defaults write com.apple.menuextra.battery ShowTime -string "YES"

#echo "Show all filename extensions in Finder"
#defaults write NSGlobalDomain AppleShowAllExtensions -bool true

echo "Use current directory as default search scope in Finder"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

#echo "Show Status bar in Finder"
#defaults write com.apple.finder ShowStatusBar -bool true

echo "Expand save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

#echo "Expand print panel by default"
#defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

echo "Disable shadow in screenshots"
defaults write com.apple.screencapture disable-shadow -bool true

echo "Save screenshots to ~/Desktop/screenshots"
defaults write com.apple.screencapture location ~/Desktop/screenshots

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

echo "Empty Trash securely by default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

#echo "Show indicator lights for open applications in the Dock"
#defaults write com.apple.dock show-process-indicators -bool true

###############################################################################
# Time Machine                                                                #
###############################################################################

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true


###############################################################################
# Screen                                                                      #
###############################################################################

# Require password immediately after sleep or screen saver begins
#defaults write com.apple.screensaver askForPassword -int 1
#defaults write com.apple.screensaver askForPasswordDelay -int 0

#echo "Disable press-and-hold for keys in favor of key repeat"
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

#echo "Set a blazingly fast keyboard repeat rate"
#defaults write NSGlobalDomain KeyRepeat -int 0.02

#echo "Set a shorter Delay until key repeat"
#defaults write NSGlobalDomain InitialKeyRepeat -int 12

# Set the Finder prefs for showing a few different volumes on the Desktop.
#defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
#defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

#echo "Disable auto-correct"
#defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Disable opening and closing window animations
# defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

#echo "Enable AirDrop over Ethernet and on unsupported Macs running Lion"
#defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

#echo "Show Path bar in Finder"
#defaults write com.apple.finder ShowPathbar -bool true

#echo "Display full POSIX path as Finder window title"
#defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

echo "Avoid creating .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

#echo "Show item info below desktop icons"
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

#echo "Enable snap-to-grid for desktop icons"
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

############
# SAFARI
############

#echo "Disable Safari’s thumbnail cache for History and Top Sites"
#defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

#echo "Make Safari’s search banners default to Contains instead of Starts With"
#defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Remove useless icons from Safari’s bookmarks bar
# defaults write com.apple.Safari ProxiesInBookmarksBar "()"

echo "Add a context menu item for showing the Web Inspector in web views"
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true


###############################################################################
# Messages                                                                    #
###############################################################################

# Disable automatic emoji substitution (i.e. use plain text smileys)
#defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

# Disable smart quotes as it’s annoying for messages that contain code
#defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# Disable continuous spell checking
#defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
# Activity Monitor                                                            #
###############################################################################

# Show the main window when launching Activity Monitor
#defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
#defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
#defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
#defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
#defaults write com.apple.ActivityMonitor SortDirection -int 0

#iTunes

# Disable smart quotes and smart dashes as they’re annoying when typing code
#defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
#defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

#echo "Show the ~/Library folder"
#chflags nohidden ~/Library

###############################################################################
# Terminal & iTerm 2                                                          #
###############################################################################

# Only use UTF-8 in Terminal.app
#defaults write com.apple.terminal StringEncodings -array 4

# Use a Franklin theme
TERM_PROFILE='FranklinBlack';
CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')";
if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
	open "${HOME}/.config/terminal/${TERM_PROFILE}.terminal";
	sleep 1; # Wait a bit to make sure the theme is loaded
	defaults write com.apple.terminal 'Default Window Settings' -string "${TERM_PROFILE}";
	defaults write com.apple.terminal 'Startup Window Settings' -string "${TERM_PROFILE}";
fi;

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
#defaults write com.apple.terminal FocusFollowsMouse -bool true
#defaults write org.x.X11 wm_ffm -bool true

# Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
# Kill affected applications                                                  #
###############################################################################

#for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
#	"Dock" "Finder" "Mail" "Messages" "Safari" "SystemUIServer" \
#	"Terminal" "Twitter" "iCal"; do
#	killall "${app}" > /dev/null 2>&1
#done

echo "Done. Note that some of these changes require a logout/restart to take effect."

